name: ChestShop-towny

main: com.acrobot.chestshop.towny.Towny
version: ${project.version}
api-version: 1.18

author: Acrobot
description: A towny integration for ChestShop 
 
depend: [ChestShop, Towny]
